export const data = [
  {
    name: "Acacia Log",
    namespacedId: "acacia_log",
    description:
      "A log or stem is a naturally occurring block found in trees or huge fungi, primarily used as a building block, and to create planks, a versatile crafting ingredient. It comes in eight types: oak, spruce, birch, jungle, acacia, dark oak, crimson and warped.",
    image: "https://minecraft-api.vercel.app/images/blocks/acacia_log.png",
    item: "Acacia Log",
    tool: "Axe",
    flammable: true,
    transparent: false,
    luminance: 0,
    blastResistance: 2,
    price: 10,
  },
  {
    name: "Acacia Planks",
    namespacedId: "acacia_planks",
    description:
      "Planks are common blocks used as building blocks and in crafting recipes. They are one of the first things that a player can craft in Survival and Adventure modes. Two categories of planks can be differentiated: flammable Overworld planks made from tree logs, and nonflammable Nether planks made from huge fungus stems.",
    image: "https://minecraft-api.vercel.app/images/blocks/acacia_planks.png",
    item: "Acacia Planks",
    tool: "Axe",
    flammable: true,
    transparent: false,
    luminance: 0,
    blastResistance: 3,
    price: 10,
  },
  {
    name: "Acacia Wood",
    namespacedId: "acacia_wood",
    description:
      'Wood or hyphae is a block that has the log\'s "bark" texture on all six sides. It comes in 8 types: oak, spruce, birch, jungle, acacia, dark oak, crimson, and warped.',
    image: "https://minecraft-api.vercel.app/images/blocks/acacia_wood.png",
    item: "Acacia Wood",
    tool: "Axe",
    flammable: true,
    transparent: false,
    luminance: 0,
    blastResistance: 2,
    price: 10,
  },
  {
    name: "Ancient Debris",
    namespacedId: "ancient_debris",
    description:
      "Ancient debris is a rare ore found in the Nether, and is the main source of netherite scraps. Its high blast resistance makes it immune to normal explosions. In item form, it floats on lava and cannot be burned by any form of fire.",
    image: "https://minecraft-api.vercel.app/images/blocks/ancient_debris.png",
    item: "Ancient Debris",
    tool: "Pickaxe",
    flammable: false,
    transparent: false,
    luminance: 0,
    blastResistance: 1200,
    price: 100,
  },
  {
    name: "Andesite",
    namespacedId: "andesite",
    description:
      "Andesite is a block of igneous rock, most often found in large pockets in the ground.",
    image: "https://minecraft-api.vercel.app/images/blocks/andesite.png",
    item: "Andesite",
    tool: "Pickaxe",
    flammable: false,
    transparent: false,
    luminance: 0,
    blastResistance: 6,
    price: 15,
  },
  {
    name: "Barrel",
    namespacedId: "barrel",
    description:
      "A barrel is a fisherman's job site block, used to store items. It functions like a single chest although it requires no air space above it to be opened.",
    image: "https://minecraft-api.vercel.app/images/blocks/barrel.png",
    item: "Barrel",
    tool: "Axe",
    flammable: false,
    transparent: false,
    luminance: 0,
    blastResistance: 2.5,
    price: 15,
  },
  {
    name: "Basalt",
    namespacedId: "basalt",
    description: "Basalt is an igneous rock found in the Nether.",
    image: "https://minecraft-api.vercel.app/images/blocks/basalt.png",
    item: "Basalt",
    tool: "Pickaxe",
    flammable: false,
    transparent: false,
    luminance: 0,
    blastResistance: 4.2,
    price: 20,
  },
  {
    name: "Bee Nest",
    namespacedId: "bee_nest",
    description: "Bee nests are naturally generated blocks that house bees.",
    image: "https://minecraft-api.vercel.app/images/blocks/bee_nest.png",
    item: "Bee Nest",
    tool: "Axe",
    flammable: true,
    transparent: false,
    luminance: 0,
    blastResistance: 0.3,
    price: 10,
  },
  {
    name: "Beehive",
    namespacedId: "beehive",
    description: "Bee nests are naturally generated blocks that house bees.",
    image: "https://minecraft-api.vercel.app/images/blocks/beehive.png",
    item: "Beehive",
    tool: "Axe",
    flammable: true,
    transparent: false,
    luminance: 0,
    blastResistance: 0.6,
    price: 15,
  },
  {
    name: "Birch Log",
    namespacedId: "birch_log",
    description:
      "A log or stem is a naturally occurring block found in trees or huge fungi, primarily used as a building block, and to create planks, a versatile crafting ingredient. It comes in eight types: oak, spruce, birch, jungle, acacia, dark oak, crimson and warped.",
    image: "https://minecraft-api.vercel.app/images/blocks/birch_log.png",
    item: "Birch Log",
    tool: "Axe",
    flammable: true,
    transparent: false,
    luminance: 0,
    blastResistance: 2,
    price: 20,
  },
  {
    name: "Birch Planks",
    namespacedId: "birch_planks",
    description:
      "Planks are common blocks used as building blocks and in crafting recipes. They are one of the first things that a player can craft in Survival and Adventure modes. Two categories of planks can be differentiated: flammable Overworld planks made from tree logs, and nonflammable Nether planks made from huge fungus stems.",
    image: "https://minecraft-api.vercel.app/images/blocks/birch_planks.png",
    item: "Birch Planks",
    tool: "Axe",
    flammable: true,
    transparent: false,
    luminance: 0,
    blastResistance: 3,
    price: 10
  },
  {
    name: "Birch Wood",
    namespacedId: "birch_wood",
    description:
      'Wood or hyphae is a block that has the log\'s "bark" texture on all six sides. It comes in 8 types: oak, spruce, birch, jungle, acacia, dark oak, crimson, and warped.',
    image: "https://minecraft-api.vercel.app/images/blocks/birch_wood.png",
    item: "Birch Wood",
    tool: "Axe",
    flammable: true,
    transparent: false,
    luminance: 0,
    blastResistance: 2,
    price: 15,
  },
  {
    name: "Black Concrete",
    namespacedId: "black_concrete",
    description:
      "Concrete is a solid block available in the 16 regular dye colors.",
    image: "https://minecraft-api.vercel.app/images/blocks/black_concrete.png",
    item: "Black Concrete",
    tool: "Pickaxe",
    flammable: false,
    transparent: false,
    luminance: 0,
    blastResistance: 1.8,
    price: 30,
  },
  {
    name: "Black Concrete Powder",
    namespacedId: "black_concrete_powder",
    description:
      "Concrete powder is a gravity-affected block that is converted to concrete when touching water. It comes in the 16 regular dye colors.",
    image:
      "https://minecraft-api.vercel.app/images/blocks/black_concrete_powder.png",
    item: "Black Concrete Powder",
    tool: "Shovel",
    flammable: false,
    transparent: false,
    luminance: 0,
    blastResistance: 0.5,
    price: 25,
  },
  {
    name: "Black Glazed Terracotta",
    namespacedId: "black_glazed_terracotta",
    description:
      "Glazed terracotta is a vibrant solid block that comes in the 16 regular dye colors, obtained by smelting colored terracotta.",
    image:
      "https://minecraft-api.vercel.app/images/blocks/black_glazed_terracotta.png",
    item: "Black Glazed Terracotta",
    tool: "Pickaxe",
    flammable: false,
    transparent: false,
    luminance: 0,
    blastResistance: 1.4,
    price: 25,
  },
  {
    name: "Black Terracotta",
    namespacedId: "black_terracotta",
    description:
      "Terracotta is a block formed from clay, with a hardness and blast resistance comparable to stone. It comes in the 16 dye colors, but more dull and earthen.",
    image:
      "https://minecraft-api.vercel.app/images/blocks/black_terracotta.png",
    item: "Black Terracotta",
    tool: "Pickaxe",
    flammable: false,
    transparent: false,
    luminance: 0,
    blastResistance: 4.2,
    price: 20,
  },
  {
    name: "Black Wool",
    namespacedId: "black_wool",
    description:
      "Wool is a block obtained from sheep that can be dyed in any of the 16 different colors, which are white, orange, magenta, light blue, yellow, lime, pink, gray, light gray, cyan, purple, blue, brown, green, red, and black. Unlike blocks such as terracotta, there is no undyed wool variant.",
    image: "https://minecraft-api.vercel.app/images/blocks/black_wool.png",
    item: "Black Wool",
    tool: "Shears",
    flammable: true,
    transparent: false,
    luminance: 0,
    blastResistance: 2,
    price: 10,
  },
  {
    name: "Blackstone",
    namespacedId: "blackstone",
    description:
      "Blackstone is a dark-colored block that functions similar to cobblestone or cobbled deepslate. It can be found only in the Nether.",
    image: "https://minecraft-api.vercel.app/images/blocks/blackstone.png",
    item: "Blackstone",
    tool: "Pickaxe",
    flammable: false,
    transparent: false,
    luminance: 0,
    blastResistance: 6,
    price: 10,
  },
  {
    name: "Blue Concrete",
    namespacedId: "blue_concrete",
    description:
      "Concrete is a solid block available in the 16 regular dye colors.",
    image: "https://minecraft-api.vercel.app/images/blocks/blue_concrete.png",
    item: "Blue Concrete",
    tool: "Pickaxe",
    flammable: false,
    transparent: false,
    luminance: 0,
    blastResistance: 1.8,
    price: 15,
  },
  {
    name: "Blue Concrete Powder",
    namespacedId: "blue_concrete_powder",
    description:
      "Concrete powder is a gravity-affected block that is converted to concrete when touching water. It comes in the 16 regular dye colors.",
    image:
      "https://minecraft-api.vercel.app/images/blocks/blue_concrete_powder.png",
    item: "Blue Concrete Powder",
    tool: "Shovel",
    flammable: false,
    transparent: false,
    luminance: 0,
    blastResistance: 0.5,
    price: 20,
  },
  {
    name: "Blue Glazed Terracotta",
    namespacedId: "blue_glazed_terracotta",
    description:
      "Glazed terracotta is a vibrant solid block that comes in the 16 regular dye colors, obtained by smelting colored terracotta.",
    image:
      "https://minecraft-api.vercel.app/images/blocks/blue_glazed_terracotta.png",
    item: "Blue Glazed Terracotta",
    tool: "Pickaxe",
    flammable: false,
    transparent: false,
    luminance: 0,
    blastResistance: 1.4,
    price: 25,
  },
  {
    name: "Blue Ice",
    namespacedId: "blue_ice",
    description:
      "Blue ice is a solid block similar to packed ice and ice, but much more slippery.",
    image: "https://minecraft-api.vercel.app/images/blocks/blue_ice.png",
    item: "Blue Ice",
    tool: "Pickaxe",
    flammable: false,
    transparent: false,
    luminance: 0,
    blastResistance: 2.8,
    price: 10,
  },
  {
    name: "Blue Terracotta",
    namespacedId: "blue_terracotta",
    description:
      "Terracotta is a block formed from clay, with a hardness and blast resistance comparable to stone. It comes in the 16 dye colors, but more dull and earthen.",
    image: "https://minecraft-api.vercel.app/images/blocks/blue_terracotta.png",
    item: "Blue Terracotta",
    tool: "Pickaxe",
    flammable: false,
    transparent: false,
    luminance: 0,
    blastResistance: 4.2,
    price: 20,
  },
  {
    name: "Blue Wool",
    namespacedId: "blue_wool",
    description:
      "Wool is a block obtained from sheep that can be dyed in any of the 16 different colors, which are white, orange, magenta, light blue, yellow, lime, pink, gray, light gray, cyan, purple, blue, brown, green, red, and black. Unlike blocks such as terracotta, there is no undyed wool variant.",
    image: "https://minecraft-api.vercel.app/images/blocks/blue_wool.png",
    item: "Blue Wool",
    tool: "Shears",
    flammable: true,
    transparent: false,
    luminance: 0,
    blastResistance: 2,
    price: 15,
  },
  {
    name: "Bone Block",
    namespacedId: "bone_block",
    description:
      "Bone blocks are storage blocks equivalent to nine pieces of bone meal.",
    image: "https://minecraft-api.vercel.app/images/blocks/bone_block.png",
    item: "Bone Block",
    tool: "Pickaxe",
    flammable: false,
    transparent: false,
    luminance: 0,
    blastResistance: 2,
    price: 10,
  },
  {
    name: "Bookshelf",
    namespacedId: "bookshelf",
    description:
      "Bookshelves are decorative blocks that primarily serve to enhance enchanting with an enchanting table.",
    image: "https://minecraft-api.vercel.app/images/blocks/bookshelf.png",
    item: "Bookshelf",
    tool: "Axe",
    flammable: true,
    transparent: false,
    luminance: 0,
    blastResistance: 1.5,
    price: 20,
  },
  {
    name: "Brain Coral Block",
    namespacedId: "brain_coral_block",
    description:
      "A coral block is a solid block that comes in five variants: tube, brain, bubble, fire, and horn.",
    image:
      "https://minecraft-api.vercel.app/images/blocks/brain_coral_block.png",
    item: "Brain Coral Block",
    tool: "Pickaxe",
    flammable: false,
    transparent: false,
    luminance: 0,
    blastResistance: 6,
    price: 15,
  },
  {
    name: "Bricks",
    namespacedId: "bricks",
    description: "Bricks are a decorative building block.",
    image: "https://minecraft-api.vercel.app/images/blocks/bricks.png",
    item: "Bricks",
    tool: "Pickaxe",
    flammable: false,
    transparent: false,
    luminance: 0,
    blastResistance: 6,
    price: 20,
  },
];
